# Generated by Django 4.0.4 on 2022-08-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='msg',
            new_name='msg1',
        ),
    ]
