# Generated by Django 4.0.4 on 2022-08-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_msg_msg_msg1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='img',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
