# Generated by Django 4.0.4 on 2022-08-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='position',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
