# Generated by Django 4.0.4 on 2022-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_register_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='restaurant',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
