# Generated by Django 4.0.4 on 2022-09-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_register_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='restaurant',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
