# Generated by Django 4.0.4 on 2022-09-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_items_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ph_no',
            field=models.BigIntegerField(),
        ),
    ]
